---
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

notifications:
  email: false
  slack:
    secure: QDE52Y7qq+PEEy6xagZ/eIJ2pd/BCCq0quN41pl+iwKXO72dlNlLINuro0Mis/dNlzMrmdwKLDBsl+r0Kkqq6L7TpnnpziVX88fBvMl4PXxkfJJwSV0fiBcXBz1hJi9E/n22gOVvO1orUBMSVTx5IDzVAEssnzABrPshoReEejw=

addons:
  firefox: "31.0"

before_install: composer selfupdate

install: composer install --no-interaction

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nohup java -jar vendor/se/selenium-server-standalone/composer/bin/selenium-server-standalone.jar > /dev/null 2> /dev/null &"

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
